### ISSUE TITLE
Rome TR#6. Community Engagement Marketing

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#100]
## Tracking Issue 6 for Rome

See [Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Description

What we do to get community to engage with the community

- In addition to `Assignees`, we will engage part of our community for guidance, support and testing.

#### Tasks
*Re-arranged to order significantly here*

- Announce Rome
  - [x] Finalize the logomark for Rome
  - [x] Write blog post
  - [x] Write newsletter
  - [x] Make assets needed for the two above
  - [x] Update the (webflow) website with "next testnet section"
- Design incentive scheme for
  - [ ] Content Creators
  - [ ] Content Curators
  - [ ] Update for any other existing roles storage, validator, council
- Announce incentive system
  - [ ] Write new blog post
  - [ ] Make assets for post and promotion
  - [ ] Update payout tools
- Write new/updated technical guides for
  - [ ] Validator
  - [ ] Storage provider
  - [ ] Content Creator
  - [ ] Content Curator
  - [ ] Forum use
  - [ ] Write newsletters
- Announce launch of system
  - [ ] Write blog post
  - [ ] Write general newsletter
  - [ ] Make assets needed for the two above
  - [ ] Write roles newsletters
- Update website (main page)
  - [x] Design
  - [x] Implement
  - [x] Test
  - [x] Update status server
  - [x] Integrate and finalize all specs into a network spec document.
  - [x] Deploy
- Update website (testnet pages)
  - [ ] Design
  - [ ] Implement
  - [ ] Test
  - [ ] Deploy
- Other
  - [ ] Coordinating final launch communication with web3/parity
  - [ ] Make support plan: who is "on call" at what time?

**Comment by bwhm** [comment]
26.08.19
---

- Checked off Announcing Rome

No further updates as of now.

**Comment by bwhm** [comment]
02.08.19
--------

No changes.

**Comment by bwhm** [comment]
21.10.19
--------

- Ben to start writing what can be done at this stage, and request assets that need to be designed.

**Comment by bwhm** [comment]
28.10.19
----

- Design incentive schemes, and Announce incentive system:
   - Draft made, and assets sourced from designers.
- Announce launch of system:
  - Draft made, and assets sourced from designers.
- Update website (main page):
  - Intermediate changes made.
  - Final changes when we are getting closer to release

**Comment by bwhm** [comment]
04.11.19
---

- Rebranding will happen before `Rome` release
   - Ben to request/gather assets and test across all platforms

**Comment by bwhm** [comment]
18.11.19
---

- Nothing new

**Comment by bwhm** [comment]
23.01.20
---

- New website deployed, with new branding
- Rome specific parts outstanding (awaiting release)

**Comment by bwhm** [comment]
11.02.20
--

- Design incentive scheme:
   - Needs to review -> and make dynamic. (Ben/Martin)
- Announce incentive system:
  - Blog draft to be published (Ben/Martin)
- Assets for blogs and newsletters:
  - Ensure we have all assets needed ahead of time (Ben)
- Coordination of release
  - Needs review  (Ben/Martin)
