### ISSUE TITLE
Rome TR#8. Release/Launch Operations

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#102]
## Tracking Issue 8 for Rome

See Rome Release Plan for information about these.

#### Description

All that is required to get the team done and product out the right way and to the right deadline!

- In addition to `Assignees`, we will engage part of our community for guidance, support and testing.

#### Tasks
- Pioneer placeholder
  - [ ] Replace testnet.joystream.org/ with a placeholder in the days from Acropolis is "closed" until "Rome is launched. (Martin)
- Finalize and publish the requirements, procedure and checklists for the
  - [ ] Sub-System Test (Add link to Issue)
  - [ ] Final Test (Add link to Issue)
- Perform the following tests (T-KR`n` 0.05, 0.05)
  - [ ] Sub-System Test
  - [ ] Final Test
- Finalize and publish an exhaustive Release Checklist
  - [ ] Release Checklist (Add link to Issue)

After the Release Checklist is completed, a status check will be part of the daily standup until Rome is live.

**Comment by bwhm** [comment]
26.08.19
---

- Not reviewed.

**Comment by bwhm** [comment]
02.08.19
--------

- No changes.
