### ISSUE TITLE
Rome: Live Milestones

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#103]
## Live Milestones

The Rome Release Plan contains a set of Milestones, with a target date for each. Experience have shown that:
- we might not be able to follow these
- we may want to add or remove certain items
- we may want to adjust the scope of each milestone

This approach, like with `Tracking Issues`, gives us some flexibility and will make it easier to keep track of our progress.

[Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome)

#### Live Milestone Table

| Live Date |   Event                                                          |Completed Date|
|:---------:|------------------------------------------------------------------|:------------:|
| 21.08.19  | [Rome Announced](#rome-announced)                                            | 22.08.19    |
| 07.10.19  | [Working Specs](#working-specs)                                        |      07.10.19   |
| 02.03.20 | [Produce Sub-System Test Checklist](#produce-sub-system-test-checklist) | 02.03.20 |
| 05.03.20 | [Perform Sub-system Test](#perform-sub-system-test)                      | 05.03.20 |
| 09.03.20  | [Produce Final Test Checklist](#produce-final-test-checklist)            | 10.03.20 |
| 09.03.20 | [Produce Release Checklist](#produce-release-checklist)                  |      NA      |
| 09.03.20 | [Snapshot and kill Acropolis*](#snapshot-and-kill-acropolis) | 09.03.20 |
| 10.03.20  | [Perform Final Test](#perform-final-test)                                | 10.03.20 |
| 12.03.20  | [Launch Ready](#launch-ready)                                    |      NA      |
| 16.03.20  | [Release](#release)                                              |      NA      |

#### Rome Announced

- **Description:** Announce the Rome upcoming testnet, with release plan and theme, and website update.
- **Tasks:**
  - See [Tracking Issue 6.](https://github.com/Joystream/joystream/issues/100)
- **Target Date:** 21.08.19
- [x] **Completed Date:** 22.08.19

#### Working Specs

- **Description:** Create and mark for review, a PR for the Rome specs
- **Tasks:**
  - See [Tracking Issue 1.](https://github.com/Joystream/joystream/issues/95)
  - See [Tracking Issue 2.](https://github.com/Joystream/joystream/issues/96)
- **Product:** [Specs](https://github.com/Joystream/joystream/tree/master/testnets/rome/specification)
- **Target Date:** 26.08.19
- [x] **Completed Date:** 07.10.19

#### Produce Sub-System Test Checklist

- **Description:** Finalize and publish the requirements, procedure and checklists for the [Sub-System Test](#perform-sub-system-test)
- **Tasks:**
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
- **Target Date:** 14.10.19
- [x] **Completed Date:**  02.03.20

#### Perform Sub-system Test

- **Description:** Test all sub-systems/software separately on the [`staging-reckless`](#staging-testnets) testnet(s)
- **Manager:** **Martin**
- **Tasks:**
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
  - See Sub-System Test Checklist (Add link to Issue)
- **Target Date:** 18.10.19
- [ ] **Completed Date:**  05.03.20

**Note** After this test, only bugfix PRs can be merged to master branch of relevant repos.

#### Produce Final Test Checklist

- **Description:** Finalize and publish the requirements, procedure and checklists for the [Final Test](#perform-final-test)
- **Manager:** **Martin**
- **Tasks:**
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
- **Target Date:** 21.10.19
- [ ] **Completed Date:** 10.03.20

#### Perform Final Test

- **Description:** Upgrade the [`staging-lts`](#staging-testnets) testnet runtime to "Rome", and perform a full feature test.
- **Manager:** **Martin**
- **Tasks:**
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
  - See Final Test Checklist (Add link to Issue)
- **Target Date:** 25.10.19
- [ ] **Completed Date:** 10.03.20

#### Produce Release Checklist

- **Description:** Finalize and publish the checklist for the [Release](#release)
- **Manager:** **Martin**
- **Tasks:**
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
  - See Release Checklist (Add link to Issue)
- **Target Date:** 28.10.19
- [ ] **Completed Date:** NA

#### Snapshot and Kill Acropolis

- **Description:** Take a snapshot of the Acropolis Chain State, and stop all Jsgenesis hosted infrastructure.
- **Manager:** **Martin**
- **Tasks:**
  - See [Tracking Issue 6.](https://github.com/Joystream/joystream/issues/100)
  - See [Tracking Issue 7.](https://github.com/Joystream/joystream/issues/101)
  - See Release Checklist (Add link to Issue)
- **Target Date:** 28.10.19
- [ ] **Completed Date:** Snapshot - 09.03.20

#### Launch Ready

- **Description:** Prepare and finalize **all** communications, website, guides and infrastructure.
- **Manager:** **Martin**
- **Tasks:**
  - See Release Checklist (Add link to Issue)
- **Target Date:** 01.11.19
- [ ] **Completed Date:** NA

#### Release
- **Description:** Launch and deploy all necessary nodes/tools/infrastructure
- **Manager:** **Martin**
- **Tasks:**
  - See Release Checklist (Add link to Issue)
- **Target Date:** 04.11.19
- [ ] **Completed Date:** NA

**Comment by bwhm** [comment]
08.10.19
--------

- Checked off `Working Spec`
- Pushed some dates +/- one week to the future.

**Comment by bwhm** [comment]
17.10.19
-------

Updated live milestones

**Comment by bwhm** [comment]
13.11.19
----

Updated live milestones

**Comment by bwhm** [comment]
01.03.20
---

Updated live milestones
