### ISSUE TITLE
Rome release checklist

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#181]
# Pre Release

## Guides
[Write and review](https://github.com/Joystream/helpdesk/pull/47):
- [x] Validator (Martin) - pending review
- [x] Storage (Martin) - pending review
- [x] Council (Martin)
- [x] Curator (Martin)
- [x] Creator (Ben)

## Communication
Write/update:
- [x] [From Acropolis to Rome](https://blog.joystream.org/from-acropolis-to-rome/)
- [x] [Incentives](https://blog.joystream.org/rome-incentives/)
- [x] Launch post (Ben)
- [x] Main Newsletter (Ben)
- [x] Role Newsletters (Ben)
- [x] Contact Substrate team
- [x] Website (Ben)

## Infrastructure
Setup:
- [x] Kill Acropolis (Mokhtar)
- [x] Frontpage (Mokthar)
- [x] Publish binaries (Mokhtar)
- [x] Update Faucet - payouts and source (Mokhtar)

## Repos
Prepare to merge:
- [x] Node (Mokhtar)
- [x] Storage (Mokhtar)
- [ ] Content Directory (Martin)
- [ ] VS-JS (Mokhtar)

# Soft launch:
Verify:
- [x] Content Directory (Martin)
- [x] Keys (Martin)
- [x] Faucet (Martin)
- [x] Pioneer (Martin)
- [x] Status server (Martin)

# Post Release

## Chain, Parameters
- Node
  - [x] Update README on master - how to connect to rome (Mokhtar)
  - [x] Add chain file to release page (Mokhtar)
  - [x] Validator nodes (Mokhtar)
- Parameters
  - [x] Update Storage staking params (Martin)
  - [x] Update Storage slots (Martin)
  - [x] Delay council 2 days (Martin)
  - [ ] Update council min stakes (Martin)

## Infrastructure
- Pioneer
  - [x] Host RPC on two nodes (w/load balancer) (Mokhtar)
  - [x] Host Pioneer on Netlify (Mokhtar)
- Storage node
  - [x] Host/setup one Storage Provider (Mokhtar)
  - [x] Host/setup one Storage Discovery (Mokhtar)
- Content
  - [x] Set Content Lead (Mokhtar)
  - [x] Set Content Directory (Mokhtar)
  - [ ] Job opening (Ben)

## Communication
Publish:
- [x] Launch post (Ben)
- [x] Main Newsletter (Ben)
- [x] Role Newsletters (Ben)
- [x] Twitter (Ben)
- [x] Reddit (Ben)

## Payouts
- [ ] Status server update to include total storage (Martin)
- [ ] Update payout scripts (Martin)
