### ISSUE TITLE
Constantinople - Live Milestones

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#205]
## Live Milestones

This issue contains a list of the milestones for the Constantinople Release.

|Target Date|   Event                          |  Involved                    | Completed |
|:---------:|:--------------------------------:|:----------------------------:|:---------:|                 
|03.04.20   |Constantinople Announced          | Ben, Martin                  |   13.04.20    |
|14.04.20   |Implement "Key" Proposals         | Francesco, Shamil      |  20.04.20    |
|21.04.20   |Implement "Important" Proposals   | Francesco, Shamil      |  27.04.20   |
|24.04.20   |All Parameters Set                | Bedeho, Ben, Martin          |   04.05.20   |
|29.04.20   |Complete Sub-system Test          | All                          |   06.05.20    |
|05.05.20   |Complete Final Test               | All                          |   `NA`    |
|08.05.20   |Launch Ready                      | All                          |   `NA`    |
|11.05.20   |Release                           | All                          |   `NA`    |

#### Constantinople Announced

- **Description:** Announce the upcoming "Constantinople" testnet, with release plan and theme, and website update.
- **Issue(s):**
  - [Operations - 1](https://github.com/Joystream/communications/issues/44)
- **Target Date:** 03.04.20
- [x] **Completed Date:** 13.04.20

#### Implement "Key" Proposals

- **Description:** Implement the "key" set of proposals in runtime and pioneer. See [here](#234)
- **Tasks:**
  - Runtime - 1 (`NA`)
  - [Runtime - 2](https://github.com/Joystream/substrate-runtime-joystream/issues/207)
  - [Runtime - 3](https://github.com/Joystream/substrate-runtime-joystream/issues/209)
  - [Pioneer - 1](https://github.com/Joystream/apps/issues/343)
  - [Pioneer - 2](https://github.com/Joystream/apps/issues/344)
  - [Pioneer - 3](https://github.com/Joystream/apps/issues/345)
- **Target Date:** 14.04.20
- [x] **Completed Date:** x

#### Implement "Important" Proposals

- **Description:** Implement the "important" set of proposals in runtime and pioneer. See [here](#234)
- **Tasks:**
  - [Runtime - 1](https://github.com/Joystream/substrate-runtime-joystream/issues/246)
  - [Runtime - 2](https://github.com/Joystream/substrate-runtime-joystream/issues/244)
  - [Runtime - 3](https://github.com/Joystream/substrate-runtime-joystream/issues/158)
  - [Runtime - 4](https://github.com/Joystream/substrate-runtime-joystream/issues/242)
  - [Runtime - 5](https://github.com/Joystream/substrate-runtime-joystream/issues/243)
  - [Runtime - 6](https://github.com/Joystream/substrate-runtime-joystream/issues/245)
  - [Runtime - 7](https://github.com/Joystream/substrate-runtime-joystream/issues/237)
  - [Runtime - 8](https://github.com/Joystream/substrate-runtime-joystream/issues/240)
  - [Runtime - 9](https://github.com/Joystream/substrate-runtime-joystream/issues/206)
  - [Pioneer - 1](https://github.com/Joystream/apps/issues/349)
  - [Pioneer - 2](https://github.com/Joystream/apps/issues/347) (rename)
  - [Pioneer - 3](https://github.com/Joystream/apps/issues/348) (rename)
  - [Pioneer - 4](https://github.com/Joystream/apps/issues/357)
  - [Pioneer - 5](https://github.com/Joystream/apps/issues/346)
- **Target Date:** 21.04.20
- [x] **Completed Date:** 27.04.20

#### All Parameters Set

- **Description:** Set all parameters for the Constantinople chain.
- **Tasks:**
  - [Operations - 1](https://github.com/Joystream/joystream/issues/186)
  - [Operations - 2](https://github.com/Joystream/joystream/issues/189)
  - [Runtime - 1](https://github.com/Joystream/substrate-runtime-joystream/issues/210)
  - [Runtime - 2](https://github.com/Joystream/substrate-runtime-joystream/issues/235)
  - [Runtime - 3](https://github.com/Joystream/substrate-runtime-joystream/issues/236)
- **Product:** [Specs](https://github.com/Joystream/joystream/tree/master/testnets/rome/specification)
- **Target Date:** 24.04.20
- [x] **Completed Date:** 04.05.20

#### Complete Sub-system Test

- **Description:** Test all sub-systems/software separately on the [`staging-reckless`](#staging-testnets) testnet(s)
- **Manager:** **Martin**
- **Tasks:**
  - [Operations - 1](https://github.com/Joystream/joystream/issues/200)
  - [Operations - 2](https://github.com/Joystream/joystream/issues/201)
  - And most tasks in [Pioneer](https://github.com/orgs/Joystream/projects/12) and [Runtime](https://github.com/orgs/Joystream/projects/10) projects
- **Target Date:** 29.04.20
- [x] **Completed Date:** 06.05.20

**Note** After this test, only bugfix PRs can be merged to master branch of relevant repos.

#### Complete Final Test

- **Description:** Upgrade the [`staging-lts`](#staging-testnets) testnet runtime to "Constantinople", and perform a full feature test.
- **Manager:** **Martin**
- **Tasks:**
  - [Operations - 1](https://github.com/Joystream/joystream/issues/200)
  - [Operations - 2](https://github.com/Joystream/joystream/issues/202)
  - And most tasks in [Pioneer](https://github.com/orgs/Joystream/projects/12) and [Runtime](https://github.com/orgs/Joystream/projects/10) projects
- **Target Date:** 05.05.20
- [ ] **Completed Date:** NA

#### Launch Ready

- **Description:** All pre-release items checked-off, and have a checklist for _all_ tasks to be performed before/during/after release.
- **Tasks:**
  - See Release Checklist (Add link to Issue)
- **Target Date:** 08.05.20
- [ ] **Completed Date:** NA

#### Release
- **Description:** Launch and deploy all necessary nodes/tools/infrastructure
- **Tasks:**
  - See Release Checklist (Add link to Issue)
- **Target Date:** 11.05.20
- [ ] **Completed Date:** NA

**Comment by bwhm** [comment]
Update 14.04.20
- Operations: 
  - Todo: 28
  - WIP: 3
  - Review/Done: 4
- Runtime:
  - Todo: 3
  - WIP: 2
  - Review/Done: 36
- Pioneer:
  - Todo: 20
  - WIP: 1
  - Review/Done: 8
