### ISSUE TITLE
Rome TR#1. New Infrastructure Runtime Modules

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#95]
## Tracking Issue 1 for Rome

See [Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Description

Some core changes need to be done on the runtime to enable a new more flexible role infrastructure now and in the future.

#### Tasks

- staking module, (T-KR2)
  - [x] specify (bedeho), #109 , [Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/staking-module.md)
  - [x] review (mokhtar)
  - [x] implement (mokhtar), Joystream/substrate-stake#1
  - [x] testing (mokhtar)
- rewards (recurring) module (T-KR2)
  - [x] specify (bedeho), #93 , [Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/recurring-reward-module.md)
  - [x] review (mokhtar)
  - [x] implement (mokhtar), Joystream/substrate-recurring-reward#1
  - [x] testing (mokhtar)
- minting module (T-KR2)
  - [x] specify (bedeho), #106 , [Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/token-mint-module.md)
  - [x] review (mokhtar)
  - [x] implement (mokhtar), Joystream/substrate-token-minting#1
  - [x] testing (mokhtar)
- hiring module (T-KR2)
  - [x] specify (bedeho), #108 , [Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/hiring-module.md)
  - [x] review (mokhtar)
  - [x] implement (bedeho), 
  - [ ] testing (bedeho/shamil), [PRs](https://github.com/Joystream/substrate-hiring-module/pulls)
- membership module (T-KR1)
  - [x] specify (bedeho), #112 , [Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/membership-module.md)
  - [x] review (mokhtar)
  - [x] implement (mokhtar), Joystream/substrate-runtime-joystream#81
  - [x] testing (mokhtar)

**Comment by bwhm** [comment]
Staking Module:
- Issues addressed.
- Bedeho to implement.

Rewards Module:
- Mokhtar to implement

Minting:
- Mokhtar to implement (?)

Hiring:
- Mokhtar to review.
- Bedeho to implement.

- Off-chain vs On-chain (keep it on-chain for now)

**Comment by bwhm** [comment]
02.09.19
--------

Staking Module:
- Has been reviewed

Rewards Module:
- Has been reviewed

Minting Module:
- Has been reviewed
- Spec checked off.

Hiring Module:
- Has **not** been reviewed

Implementation will not start this week.

**Comment by bwhm** [comment]
09.09.19
--------

Went through all modules. Added (and checked off) review checkmark for each.

**Comment by bwhm** [comment]
16.09.19
--------

- Minting module:
   - Checked off implementation and testing ([repo](https://github.com/Joystream/substrate-token-minting))

- Membership module:
   - Checked off implementation and testing (PR:Joystream/substrate-runtime-joystream#81 )

- Small changes to the staking and hiring module (spec)
- Mokhtar to start implementing the rewards module today.
- Hoping to be have all modules ready and merged before next tracking issue meeting.

**Comment by bwhm** [comment]
23.09.19
--

- Staking module:
   - Implementation changed from Bedeho to Mokhtar
   - Draft PR open (small changes expected. will be ready for review later this week)
- Rewards module:
   - Checked off implementation and testing
- Membership module:
   - Some small comments from bedeho, will not lead to significant changes.
   - Will be reviewed AFTER Joystream/substrate-node-joystream#83, as it builds on this.

**Comment by bwhm** [comment]
01.10.19
--------

- Staking module:
   - Open for review, but minor changes expected
- Hiring module:
   - Implementation WIP, added link to draft PR
- Membership module:
   - Some changes to be expected

Some concerns raised regarding the status vs. the roadmap. Will review #103 this week.

**Comment by bwhm** [comment]
07.10.19
--------

- Staking module:
   - small tweaks needed to implementation
   - more tests to be added 
- Rewards and Minting modules:
   - small tweaks made
- Hiring module:
   - implementation wip, to be completed this week
- Membership module:
   - Same changes to be made based on review
   - Key hierarchy/structure to be documented

**Comment by bwhm** [comment]
14.10.19
--------

- Staking module:
   - one new commit 
- Hiring module:
   - close to finish implementation
   - no tests
   - changes may be needed based on content directory module (#96)

**Comment by bwhm** [comment]
21.10.19
----

- Staking module:
   - small tweaks needs review (bedeho)
- Hiring module:
   - implementation finished
   - mokhtar reviewing
   - tests to be added next week (bedeho), or if required by mokhtars work on the content directory module in #96

**Comment by bwhm** [comment]
28.10.19
-------

- Hiring module: 
   - bedeho to add tests later
- Membership module:
   - Led to a broader discussions ref issue #136 
   - Mokhtar to draft up a coherent proposal addressing the issues and a path forward

**Comment by bwhm** [comment]
04.11.19
---

- Staking module:
	- API changes
	- bedeho+mokhtar to resolve 
- Rewards module:
	- merged to dev
- Minting module:
	- merged to dev
- Hiring module:
	- tbd reviewed
- Membership module:
	- merged to dev

---

- Also discussed: 
   - Problems with building our runtime. Needs to be addressed
   - The list in #136 was considered to comprehensive for Rome, considering:
      - We are already behind on release
      - Some of the work requires more thinking, and can be resolved in Pioneer for now.
      - Long term, some of the problems might be resolved by [this](Joystream/substrate-versioned-store-permissions-module#4) proposal.
   - We decided to stick with ONLY batching transactions for Rome.

**Comment by bwhm** [comment]
11.11.19
---

- Hiring module:
	- tests and review remaining

**Comment by bwhm** [comment]
18.11.19
----

- Hiring Module:
	- mokhtar has reviewed, and left some feedback
	- no tests written yet.

- Membership Module:
	- some changes made, to be reviewed

**Comment by bwhm** [comment]
25.11.19
----

No updates of significance

**Comment by bwhm** [comment]
02.12.19
---

- Hiring Module:
   - Bedeho to write tests and/or rewrite based on outside review.

**Comment by bwhm** [comment]
17.12.19
---

- Hiring Module:
   - Bedeho to complete writing (or delegating tests) and potential improvements.

**Comment by bwhm** [comment]
06.01.20
----

- No updates during the holidays (24.12 and 31.12)

- Hiring Module:
   - some improvement in the implementation (shamil)
   - tests to be finalized by end of week (shamil)

**Comment by bwhm** [comment]
23.01.20
---

- Hiring Module:
   - Bedeho and Shamil to finalize improvements and testing

**Comment by bwhm** [comment]
11.02.20
--

- Hiring Module:
   - Done, but some additional work being done here by Shamil
