### ISSUE TITLE
Rome TR#2. Media System (Static Parts)

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#96]
## Tracking Issue 2 for Rome

See [Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Description

This covers the base, or static, parts of the new media system.

#### Tasks

- versioned data store module, (T-KR3,4,5)
  - [x] specify (bedeho), #74 ,[Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/versioned-store.md)
  - [x] review (alex,mokhtar)
  - [x] implement (alex, Joystream/substrate-versioned-store#9)
  - [x] testing (alex)
- permissions module, (T-KR1)
  - [x] specify (mokhtar), #92 ,[Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/versioned-store-permissions.md)
  - [x] review (bedeho)
  - [x] implement (mokhtar)
  - [x] testing (mokhtar)
- content directory working group module, (T-KR1)
  - [x] specify (bedeho),  #107 ,[Merged](https://github.com/Joystream/joystream/blob/master/testnets/rome/specification/runtime/content-directory-working-group.md)
  - [x] review (mokhtar)
  - [x] implement (bedeho), Joystream/substrate-runtime-joystream#87
  - [ ] testing (bedeho)
- Curation:
  - Curator Lead (T-KR2 0.5)
     - Tools for content Joystream/versioned-store-js#1
       - [x] JS library for versioned store (alex)
       - [x] Tool for making extrinsics that creates classes, schemas and entities  (alex)
       - [x] Improve UX (martin)
       - [x] Implement permissions module in tool (mokhtar)
  - Curators group - Pioneer
       - Joining flow (T-KR2 0.2 + C-KR2 0.5)
          - [x] mockup (paul)
          - [x] review (bedeho)
          - [x] components & styling (paul)
          - [ ] state & backend integration (paul)
       - View status of curator group: list of actors  (T-KR2 0.1)
         - [x] mockup (paul)
         - [x] review (bedeho)
         - [x] components & styling (paul)
         - [x] state & backend integration (paul)
       - Policing and editing flow (T-KR2 0.2 + C-KR2 0.5)
         - [x] mockup (alex)
         - [x] review (martin/bedeho)
         - [x] components & styling (alex)
         - [ ] state & backend integration (alex)

**Comment by bwhm** [comment]
26.08.19
--------

Staking Module:
- Issues addressed.
- Bedeho to implement.

Rewards Module:
- Mokhtar to implement

Minting:
- Mokhtar to implement (?)

Hiring:
- Mokhtar to review.
- Bedeho to implement.

- Off-chain vs On-chain (keep it on-chain for now)

**Comment by bwhm** [comment]
02.09.19
--------

Versioned Data Store Module:
- Bedeho to review this week
- Discussion regarding arrays
- Alex to find the best way of implementing them
- Discussed the value of naming the entities (no, for now)
- Discussed whether to have the runtime decide indexing (no, for now)

Permission Module:
- Bedeho has reviewed, some discussion still to be had

Channel Module:
- Added to this tracking issue
- Might be merged with CDM

Content Directory Module:
- Still WIP

---

Remaining items unchanged.

**Comment by bwhm** [comment]
09.09.19
--------

- [Channel module](#113) to be replaced by a channel schema.
- Added as a task to [TR#3](#97 

Nothing else changed.

**Comment by bwhm** [comment]
16.09.19
--------

- Alex to make small addition to VSD module.
- Some discussion whether to force or make optional reference to schema version in VSD (decided to wait)
- Permission module to be implementing permissions next week (after TR1 is "finished")
- Content directory module spec to be completed this week

- Curator lead
    - Added a task for JS library (WIP)
    - Split between content and working group tooling

- Remaining Curator related tasks will wait until after content directory module is spec'd

**Comment by bwhm** [comment]
23.09.19
--

- Bedeho to finish review of versioned data store module today. Alex to add final check.
- Content directory module spec completed.
- Alex working on curator lead tools (JS libraby and CLI), to be finished this week.
- Some discussions regarding the scope of curator role and curation tools in pioneer. Will go with a lightweight approach as of now, requiring more "offchain" communication

**Comment by bwhm** [comment]
01.10.19
--------

- versioned data store module:
   - checked off testing
- Curation:
   - Decided to wait completing the CLI too (Curator Leadl, as the current functionality is enough for launch.
   - Decided not to create any additional CLI tool for Curator Lead, and use Pioneer.
   - Rewritten to reflect these changes.

**Comment by bwhm** [comment]
07.10.19
--------

- versioned data store module:
  - to be migrated to v2
- permissions module:
   - will start implementation on Tue/Wed
   - complete by end of week
- content directory module:
   - not reviewed, implementation starting by end of week (hopefully)
- Curator Lead - tools for content (vs-js):
  - new commit later
  - martin working on CLI
- Curator (Lead) Pioneer:
  - Discussions whether should start on this, or items from TR3 #97 next

**Comment by bwhm** [comment]
14.10.19
--------

- versioned data store module:
  - migrated to v2
  - mokhtar suggests some changes to structure, won’t impact vs-js
- permissions module:
   - roughly 30% complete
   - should complete by end of 15th
- content directory “working group” module:
   - will review whom to implement (mokhtar/bedeho) on the 16th
   - depends on progress and priorities
- Curator Lead - tools for content (vs-js):
  - tooling good enough for launch. no real CLI though
- Curator (lead) Pioneer:
  - alex to start mockups this week

**Comment by bwhm** [comment]
21.10.19
--------

- versioned data store module:
  - small tweaks needs review (bedeho)
- permissions module:
   - done
   - alex to review
- content directory “working group” module:
   - mokhtar to review in implement
- Curator Lead - tools for content (vs-js):
  - tooling good enough for launch. no real CLI though
  - alex to implement permissions module, and update types to substrate v2
- Curator Pioneer:
  - paul started mockups of hiring/firing flow, and joining flow.

**Comment by bwhm** [comment]
28.10.19
------

- permissions module:
   - small additions needed ref #136 
   - alex to review

- Curators group - Pioneer
   - mockups and review completed for joining flow and working group list 
   - editing more or less same as uploading flow (ref #97) 
   - policing needs more thinking

**Comment by bwhm** [comment]
04.11.19
------

- versioned data store module:
   - no changes ref [TR1](https://github.com/Joystream/joystream/issues/95#issuecomment-549345381)
- permissions module:
   - mokhtar to implement batching and `5.` from #136
- content directory working group module:
   - WIP, but probably weeks away from final
- Curation:
   - Tools for content:
       - Mokhtar to add batching
   - Curators group - Pioneer:
      - Working components & styling for joining flow and status view
      - Editing requires little more than uploading ref #97
      - Curation needs thinking.

**Comment by bwhm** [comment]
11.11.19
------

- permissions module:
   - batching of `createEntity`, `addSchemaSupportToEntity`, `updateEntity` implemented.
- Curation:
   - Tools for content:
       - Mokhtar to add batching in the tool.
   - Curators group - Pioneer:
      - Paul working on components & styling for joining flow and status view
      - Curation still needs thinking.

**Comment by bwhm** [comment]
18.11.19
----

- Permissions module:
	- awaiting review (bedeho)
- Content directory working group module:
   - no point in reviewing specs, too outdated

- Curation:
   - Tools for content:
      - Some issues with dependencies (substrate and polkadot API), but should be ready soon.
      - Few changes, mostly additions
   - Curators group - Pioneer:
      - Curation still needs thinking.

---

Some discussion on git workflow.

**Comment by bwhm** [comment]
25.11.19
----

- Content directory working group module:
   - Still wip.
- Curation:
   - Tools for content
       - Permissions added to tool
   - Pioneer
       - WIP

**Comment by bwhm** [comment]
02.12.19
---

- Content directory working group module:
   - Implementation checked off.
   - Bedeho to write tests, and mokhtar to review.

- Curators group - Pioneer 
   - Joining flow: 
        - components & styling checked off
        - Paul to work on state & backend integration

**Comment by bwhm** [comment]
17.12.19
---

- Content directory working group module:
   - Review checked off (Mokhtar)
- Tools for content:
   - Improvements (Mokhtar and Martin)
- Curators group - Pioneer:
    - Joining flow & View status of curator group
      - Paul to complete State and Backend Integration

**Comment by bwhm** [comment]
06.01.20
----

- No updates during the holidays (24.12 and 31.12)

- Content Directory Working Group Module:
   - Tests should be done by end of week (bedeho)

- Pioneer:
   - Policing and editing flow:
        - This needs more thinking (mokthar)
   - All others:
        - Little progress during the holidays

**Comment by bwhm** [comment]
23.01.20
---

- Curators group - Pioneer
    - Joining flow 
        - State and backend integration hopefully completed early next week (paul)
    - View status of curator group: list of actors
        - State and backend integration hopefully completed early next week (paul)

**Comment by bwhm** [comment]
11.02.20
--

- Content directory working group module:
   - Done, but there are open PRs with bugfixes and enhancements
- Curation:
  - Tools for content:
       - Needs Joystream types to be updated to allow it to work with newest version of
runtime
       - Needs ~1 more days work in total (Mokhtar)
  - Curators group - Pioneer
       - Joining flow
          - 6-7 days left, state & backend integration (Paul)
      - View status of curator group
            - State & backend integration done (checked off)
     - Policing and editing flow
          - mockup, review & components & styling done (checked off)
          - Decided to use same UI as for content creators ([ref TR3](https://github.com/Joystream/joystream/issues/97))
          - 6-7 days left, state & backend integration (Alex)
