### ISSUE TITLE
Rome TR#3. Media System (Dynamic Parts)

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#97]
## Tracking Issue 3 for Rome

See [Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Description

The actual media system we chose to introduce at release, based on our new flexible runtime architecture, and how users interact with this in our primary app: Pioneer.

#### Tasks

- New schemas  (T-KR3 0.2, 0.1, 0.15, 0.15, 0.15)
    - [x] General schema design template, in a [json-schema](https://json-schema.org/) format (alex)
    - [x] 3 new content type schemas: Decide on actual type to support, based on availability of content and richness of schemas. (martin)
    - [x] Design `video` schema (martin)
    - [x] ~~Design `music` (album) schema (martin)~~
    - [x] ~~Design `book` schema (martin)~~ 
           - Decided to drop these for release to avoid extending the release cycle further. See [TR4](#98)
- Joystream Content System resources repo, #130
    - [x] Current status of the system (martin)
    - [x] High level explanation (martin)
    - [ ] Examples (martin)
- Data Directory:
    - [x] Decide on new set of data_types required data directory.
    - [x] Decide on how the data directory should look after schemas.
- Define the following _for each type_ in Pioneer. (let each checkbox be status across all types)
  - Overview of subset of content directory for specific content type: no search for now, just pagination!
    - [x] mockup (martin)
    - [x] review (bedeho/alex)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)
  - Item view & playback experience: different roles (creator, curator, viewer) may see different things.
    - [x] mockup (martin)
    - [x] review (bedeho/alex)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)
- A top level overview view of the entire directory: should we have featured content or creators?
    - [x] mockup (martin)
    - [x] review (alex)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)
- Creator profile in Pioneer
  - Extend membership flow: how you setup a creator channel (T-KR1 0.25)
    - [x] mockup (bedeho)
    - [x] review (alex)
    - [x] components & styling (alex/mokhtar)
    - [ ] state & backend integration (alex/mokhtar)
  - Publishing/unpublish flow for creator (T-KR1 0.25)
    - [x] mockup (alex)
    - [x] review (bedeho)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)
  - Third party view of profile: e.g. see all content categorized, cover photo (T-KR1 0.25)
    - [x] mockup (bedeho)
    - [x] review (alex)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)
  - Owner view + editing flow (T-KR1 0.25)
    - [x] mockup (alex)
    - [x] review (bedeho)
    - [x] components & styling (alex)
    - [ ] state & backend integration (alex)

**Comment by bwhm** [comment]
26.08.19
---

decide on content types to support with schemas
- (see https://github.com/Joystream/bounties/issues/20)
- some discussion around the difference between schema and class

Decide on new set of data_types required data directory.
- tbd based on point above

Went through remaining items to get an impression of workload. After Alex has completed his work in #96, we will discuss priorities etc.

**Comment by bwhm** [comment]
02.09.19
---------

Tentative decision on content schemas:
- `video`, `podcast` and `ebook`

Decided on not adding new data_types in colossus.
Some other issues regarding colossus and the dataDirectory, that has to be resolved:
- The dataDirectory currently stores some metadata as well.  Example:
```
{"owner":"5CEw8JxuM1kh34VoocG9bqqjqs98pdA7fG5uaTtPdjzShqFb","added_at":{"block":1031855,"time":1561531158},"children_ids":[],"visibility":0,"schema":1,"json":"{\"name\":\"Spring - Blender Open Movie\",\"description\":\"\",\"thumbnail\":\"https://i.ytimg.com/vi/WhWc3b3KhnY/hqdefault.jpg\",\"keywords\":\"\"}"}
```
Discussed the format of the schemas, and how to best represent each entry as a JSON.

**Comment by siman** [comment]
> The dataDirectory currently stores some metadata as well.

It stores such information as title and description of a media file in a struct called `ContentMetadata`

**Comment by bwhm** [comment]
09.09.19
---------

- Discussed the structure of the joystream class schema
- Added new tasks
    - General schema design template, in a json-schema format
    - Tool for describing structures of the versioned data store in typescript
    - Channel schema (see #96 and #113)

**Comment by bwhm** [comment]
16.09.19
---------
- Missing JSON template for entities to be be added.
- Decided not to make any changes for the data directory (remove the forced description in pioneer)
- Mockups in progress for Creator in pioneer

**Comment by bwhm** [comment]
23.09.19
--------

- JSON templates checked off.
- Not much progress on other items, as we've had to focus on other things.

**Comment by bwhm** [comment]
01.10.19
-------

- New schemas 
   - Checked off `podcast` and `channel`
- Added tasks under "Joystream Content System resources repo"

**Comment by bwhm** [comment]
07.10.19
--------

- New schemas 
  - Progress on outstanding, but not complete
- Joystream Content System resources repo
  - WIP, depending on CLI tool in #96 
- Pioneer mockups to start after above items

**Comment by bwhm** [comment]
14.10.19
--------

- New schemas
   - All `content types` checked off, but iterations should be expected.
- Joystream Content System resources repo
   - WIP, will get back to it after finalizing the schemas
- Pioneer mockups
   - to start after above items

Other: A small issue with the vs-js (from #96 ) with adding schemas to class from json. alex to review.

**Comment by bwhm** [comment]
21.10.19
--------

- New schemas
   - Decided on replacing content type `podcast` -> `music albums`
   - Podcast to be delayed to in "in flight launch"
- Pioneer mockups
   - some tasks reassigned to bedeho

The decision regarding `podcast`/`music album` sparked a lot of discussions, ending with conclusion above.

**Comment by bwhm** [comment]
28.10.19
---

As alex was not available for a call, this _may_ be revised after his input/comments.

- New schemas:
   - `music` album schema checked off
- Pioneer mockups:
  - All are WIP, and close to finished.

**Comment by bwhm** [comment]
04.11.19
---

- Joystream Content System resources repo:
   - Should be made public today or tomorrow
- Pioneer mockups:
  - Alex started working on components & styling using netlify storybook.

**Comment by bwhm** [comment]
18.11.19
---

**Note:** 
- Comment from last week missing
- This will include both

- New schemas:
   - Decided to delay/skip `books`, as the content type is very different in terms of schemas, uploading, playback (none) and styling.

- Joystream Content System resources repo
   - [PR](https://github.com/Joystream/joystream-content-system/pull/3) opened

- Pioneer
  - Focus on uploading and playback flow.

**Comment by bwhm** [comment]
25.11.19
----

No updates of significance

**Comment by bwhm** [comment]
02.12.19
----

- Pioneer:
   - Components and styling close to complete for all (alex).
   - Start working on state and backend integration for all this week (alex)

**Comment by bwhm** [comment]
18.12.19
----

- Pioneer:
   - Refactoring and creating middleware (alex)

**Comment by bwhm** [comment]
06.01.20
----

- No updates during the holidays (24.12 and 31.12)

---

- Little progress during the holidays

**Comment by bwhm** [comment]
23.01.20
---

- Creator profile in Pioneer 
   - `Extend membership flow: how you setup a creator channel`
   - `Owner view + editing flow`
       - `components & styling` checked off for both (alex)

- `components & styling` and `state & backend integration` in progress for all other items.

More information can be found [here](https://github.com/Joystream/apps/issues/258)

**Comment by bwhm** [comment]
11.02.20
--

- New schemas :
   - Will release with `Video` only - `Music Album` added later ref [TR3](#98)
   - Add channel to schema content schema(s), as they are outside of versioned store.
- Pioneer:
  - Overview of subset of content directory for specific content type &
  - A top level overview view of the entire directory
       - Media "landing" page to display featured videos (curators decide)
       - All videos to show a full list, pagination to be added later
  - Item view & playback experience: different roles (creator, curator, viewer) may see different things.
       - Components and styling done (checked off)
  - Creator profile in Pioneer - how you setup a creator channel &
  - Third party view of profile: e.g. see all content categorized, cover photo
       - Components and styling done (checked off)
       - State & backend integration - 2 days work left (Alex)
  - Publishing/unpublish flow for creator &
  - Owner view + editing flow
       - Components and styling done (checked off)
       - State & backend integration - 3 days work left (Alex)

---

- Needs a reckless chain and permission integration for proper testing:
   - Curator editing of content to be same UI as for owner
   - Channel curation to be done by `sudo` (to be added later)
