### ISSUE TITLE
Rome TR#4. Post-Release Media System Changes

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#98]
## Tracking Issue 4 for Rome

[Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Description

The essential design goal of the media system has been to allow versioned upgradability, and we have as such decided to execute on this.

#### Tasks

- 1 or 2 new content type(s) (T-KR4)
  - [x] decide on what content type -> `Music Album` and later maybe`Podcast` (martin)
  - [x] create new schema (martin)
  - [ ] update Pioneer to support new content type (alex)
- A new schema version for existing content type (T-KR5)
  - [ ] decide on what content type (martin)
    - Will be decided based on feedback from community.
  - [ ] create new schema for content type (martin)
  - [ ] migrating objects to new schema and run it. (ben)
  - [ ] update Pioneer (alex)

**Comment by bwhm** [comment]
26.08.19
---

Some confusion around phrasing (concept -> content type). 
Behind #96 and #97 in priority.

**Comment by bwhm** [comment]
02.09.19
---------

Loose discussion on which new schema to add after launch, and which to update. Will not be planned until [TR#3](https://github.com/Joystream/joystream/issues/97) have been concluded more or less.

**Comment by bwhm** [comment]
09.09.19
---------

- Nothing new

**Comment by bwhm** [comment]
16.09.19
---------

- Nothing new

**Comment by bwhm** [comment]
23.09.19
---

- Nothing new

**Comment by bwhm** [comment]
01.10.19
--------

- Nothing new

**Comment by bwhm** [comment]
07.10.19
--------

- Assigned tasks

**Comment by bwhm** [comment]
14.10.19
--------

- 1 new content type
    - Decided on `music`
- A new schema version for existing content type 
    - Decided to wait until after release, as we expect to find limitations in multiple classes, and by extension, with content types

**Comment by bwhm** [comment]
21.10.19
--------

- 1 new content type
    - Decided on to switch `podcast` to `music album` at launch.

**Comment by bwhm** [comment]
04.11.19
---

- Nothing new

**Comment by bwhm** [comment]
11.11.19
---

- Nothing new

**Comment by bwhm** [comment]
18.11.19
---

- Nothing new

**Comment by bwhm** [comment]
25.11.19
----

No updates of significance

**Comment by bwhm** [comment]
02.12.19
----

No updates of significance

**Comment by bwhm** [comment]
17.12.19
----

No updates of significance

**Comment by bwhm** [comment]
06.01.20
----

- No updates during the holidays (24.12 and 31.12)

---

- Little progress during the holidays

**Comment by bwhm** [comment]
23.01.20
---

- No news

**Comment by bwhm** [comment]
11.02.20
--

- 1 or 2 new content type(s) :
   - `Music Album` to be added later ref [TR3](#98)
   - `Podcast` might be added later
