### ISSUE TITLE
Rome TR#5. Launch New Substrate Chain

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream-landing#99]
## Tracking Issue 5 for Rome

See [Rome Release Plan](https://github.com/Joystream/joystream/tree/master/testnets/rome) for information about these.

#### Tasks

- Upstream changes 
   - [x] Evaluate which substrate version to use (Mokhtar) 
   - [x] Migrate old runtime to working v2 chain (Mokhtar) 
   - [x] Migrate old modules to work with TBD hash of substrate v2 (Mokhtar)
   - [x] Migrate new modules to work with TBD hash of substrate v2 
      - The person that implemented the module (see #95 , #96 ) are responsible.
   - [x] Migrate pioneer to v2, Joystream/apps#240 (Mokhtar and Alex)
- Build tool to export old state and encoded as new GenesisConfig for new chain. Currently we have decided on  (Mokhtar) 
  - [x] Memberships (members will start with a small balance)
  - [x] Accounts (not balance)
  - [x] Forum (all of it)
- Other
  - [ ] Create representations for all new schemas (not in GenesisConfig) (Mokhtar/Martin)
  - [x] Update faucet server (Mokhtar)
  - [x] Update status server (Mokhtar, Martin)
  - [ ] Build and tag new node binary (Mokhtar)
  - [x] Colossus (Mokhtar)

**Comment by bwhm** [comment]
26.08.19
---
Changed the following:
- removed data objects (will not be exported)
- add schemas after launching new chain (not in genesisblock)
- add evaluating which substrate version to use

**Comment by bwhm** [comment]
02.09.19
---------

Substrate version:
- Decided to go with Substrate v2.0, unless testing shows serious issues.
- Runtime and node migrated
- Pioneer requires pulling from upstream

---

No further changes this week

**Comment by bwhm** [comment]
09.09.19
--------

- No updates

**Comment by bwhm** [comment]
17.09.19
--------

- Discussed the progress and future workload of migration to substrate v2.
- Mokhtar to migrate pioneer next week, time permitting.

**Comment by bwhm** [comment]
23.09.19
-----

- All new modules (implemented by Mokhtar, see #95) built to be compatible with v2
- Pioneer migration close to finished
- Added `colossus` under other (as the changes are API-related only)

**Comment by bwhm** [comment]
01.10.19
--------

- Added PR for pioneer update to v2

**Comment by bwhm** [comment]
07.10.19
--------

- Due to a constraint allowing only 30 modules, we must further migrate v2 to a newer commit.

**Comment by bwhm** [comment]
21.10.19
--------

- Mokhtar to decide on specific substrate v2 commit hash to target ASAP

**Comment by bwhm** [comment]
28.10.19
-----

- Decided to follow polkadot [master](https://github.com/paritytech/polkadot/commit/f35a4db47c2563ee04b4c44aed568aec96178b18) branch at time of writing as target, and revise at later date.

**Comment by bwhm** [comment]
04.11.19
---

- Nothing new

**Comment by bwhm** [comment]
04.11.19
---

- "release" commit still TBD

**Comment by bwhm** [comment]
18.11.19
---

- Nothing new

**Comment by bwhm** [comment]
25.11.19
-----

- Upstream changes 
   - Migrate pioneer to v2 done
- Build tool to export old state and encoded as new GenesisConfig for new chain.
  - Mokhtar started work on all.
- Other
  - Faucet, Status server and Colossus checked off (mokhtar)

**Comment by bwhm** [comment]
02.12.19
----

- Build tool to export old state and encoded as new GenesisConfig for new chain:
   - All three checked off (Mokhtar)

**Comment by bwhm** [comment]
17.12.19
----

- Other:
   - Build and tag new node binary
      - Mokhtar working on docker images

**Comment by bwhm** [comment]
06.01.20
----

- No updates during the holidays (24.12 and 31.12)

---

- Little progress during the holidays

**Comment by bwhm** [comment]
23.01.20
---

- No news

**Comment by bwhm** [comment]
11.02.20
--

- Build tool to export old state and encoded as new GenesisConfig for new chain.
   - Migration still working.
- Other:
  - Colossus needs support for larger file size
  - Support for removing data from Colossus to be added later
  - Needs to review default genesis config (Mokhtar/Martin/Ben)
       - Balances for existing members
       - Payouts (JOY) for `Storage Providers`, `Validators` and `Curators`
       - Staking requirements (JOY) for `Storage Providers`, `Validators?` and `Curators`
       - Smaller (relative) size of faucet tokens -> Use telegram for larger (JOY) token payouts, to avoid faucet abuse.

---

- Needs a reckless chain with permission integration for proper testing (Mokhtar)
